default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cutelycandle_development
  host: localhost
  port: 5432
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: cutelycandle_test
  host: localhost
  port: 5432
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['MY_APP_DATABASE_URL'] %>
  # database: cutelycandle_production
  # username: cutelycandle
  # password: <%= ENV["CUTELYCANDLE_DATABASE_PASSWORD"] %>
